### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by juancampa** [AngelicosPhosphoros/keyed_priority_queue#18]
Hi, thanks for the awesome work with this crate. I was updating my dependencies and wanted to understand what changed between `0.3.2` and `0.4.1` but there's nothing in the changelog. I'll read through the commits but thought you might wanted to know

**Comment by AngelicosPhosphoros** [comment]
Hi, @juancampa 
I updated minimally supported Rust version to Rust 2021 (1.56). This is a breaking change so I decided to bump semver.
Yeah, you are right, should probably mention this on changelog.

**Comment by AngelicosPhosphoros** [comment]
Updated changelog.
Thanks for remainding it to me.
https://github.com/AngelicosPhosphoros/keyed_priority_queue/blob/develop/CHANGELOG.md#2021-10-24-040

**Comment by AngelicosPhosphoros** [comment]
Also, I don't plan to drop support for older Rust versions in near future but there would be only minor patches for 0.3.x for them.

New features (if any) would be added only to 0.4.x or later.
